### ISSUE TITLE
Option to disable Hardware Acceleration

### ISSUE THREAD

**Issue by andveg38** [jacobpretorius/JustStarted#2]
I didn't know how best to contact you but my iMac GPU is struggling so disabling Chrome hardware acceleration helps in many places. It looks like JustStarted is made with Chrome. Can you add an option to disable acceleration? My Toggl project list is a bit long and when scrolling through it in JustStarted, titles disappear.

![Screen Shot 2019-09-05 at 10 53 17 AM](https://user-images.githubusercontent.com/25326004/64358191-9cf31d80-cfcb-11e9-8a5a-4535ed8bbea9.png)

**Comment by jacobpretorius** [comment]
Hey @andveg38 thanks for getting in touch :) that's an interesting problem. Yes it's made with Electron which is basically packaged Chrome in an app form. Mind if I ask how many projects do you have in Toggl?

**Comment by andveg38** [comment]
I typically have 12-15, sometimes up to 30 until I archive finished projects. Apps built like this with Electron, some have an option to disable hardware acceleration and the visual glitches stop, minus any animation and effects but helps a lot.

**Comment by jacobpretorius** [comment]
Hi again @andveg38, I've created a version of the app that has hardware acceleration turned off. You can download it here and let me know if it works for you:

https://github.com/jacobpretorius/JustStarted/releases/download/v0.9.2/JustStarted-NoGpu-0.9.2.dmg

Cheers.

**Comment by andveg38** [comment]
This works so much better for me! No more visual glitches like the image above, I can read the text on all of my projects again & scrolling doesn't make any titles disappear anymore. Thank you!!!
