### ISSUE TITLE
Update API Url Domain to api.track.toggl.com

### ISSUE THREAD

**Issue by gilberthdez** [jacobpretorius/JustStarted#3]
toggl.com or www.toggl.com will no longer be a supported entry point for the Toggl Track API check:

- https://github.com/toggl/toggl_api_docs
- https://toggl.com/blog/api-documentation-change

**Comment by jacobpretorius** [comment]
Hey, thanks for flagging this update. I just created a release (v1.0.1) addressing this update on Windows and the Mac installers will be added within the next couple of days.

**Comment by jacobpretorius** [comment]
Should be all good now.

https://github.com/jacobpretorius/JustStarted/releases/tag/v1.1.0
